# Generated by Django 5.0.4 on 2024-06-08 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('total_price_cart', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cart_state',
            fields=[
                ('cart_state_id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cart_detail',
            fields=[
                ('cart_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('total', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='cart_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart_state'),
        ),
    ]
