# Generated by Django 5.0.6 on 2024-05-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='apps/product/media/images', verbose_name='Imagen del Producto'),
        ),
    ]
